version: 1.0.{build}

branches:
  except:
    - gh-pages

skip_commits:
  message: /\[ci skip\]/

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release
  - Debug

init:
  - git config --global core.autocrlf input

clone_depth: 5
  
install:
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=../local -G "Visual Studio 15 2017 Win64" ..
  - cmake --build . --config Release --target install

before_build:
  - mkdir build && cd build
  - cmake -CMAKE_INSTALL_PREFIX=../local -G "Visual Studio 15 2017 Win64" ..

build:
  parallel: true
  project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\build\src\tests\%CONFIGURATION%\unit_tests.exe --gtest_output=xml:unit_tests.xml'

on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\unit_tests.xml))
