version: 1.0.{build}

branches:
  except:
    - gh-pages

skip_commits:
  message: /\[ci skip\]/

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release
  - Debug

init:
  - git config --global core.autocrlf input

clone_depth: 5
  
install:
  - git submodule update --init --recursive
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build && cd build
  - conan install .. -s build_type=%CONFIGURATION% --build=missing
  - cmake -G "Visual Studio 15 2017 Win64" ..

build:
  parallel: true
  project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\build\test_package\bin\unit_tests.exe --gtest_output=xml:unit_tests.xml'

on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\unit_tests.xml))
